#!/bin/bash
#Automatic Backup Linux System Files
#By Author li
#DefineVariables
SOURCE_DIR=($*)
TARGET_DIR=/data/backup/
YEAR=`date+%Y`
MONTH=`date+%m`
DAY=`date+%d`
WEEK=`date+%u`
FILES=system_backup.tgz
CODE=$?
if [ -z $SOURCE_DIR ];then
  echo -e "PleaseEnteraFileorDirectoryYouNeedtoBackup:\n--------------------------------------------\nExample$0/boot/etc......"
  exit
fi
#DetermineWhethertheTargetDirectoryExists
if [ ! -d $TARGET_DIR/$YEAR/$MONTH/$DAY ];then
  mkdir -p $TARGET_DIR/$YEAR/$MONTH/$DAY
  echo "This$TARGET_DIRCreatedSuccessfully!"
fi
#EXECFull_BackupFunctionCommand
Full_Backup(){
  if [ "$WEEK" -eq "7" ];then
    rm-rf $TARGET_DIR/snapshot
    cd $TARGET_DIR/$YEAR/$MONTH/$DAY; tar -g $TARGET_DIR/snapshot -czvf $FILES`echo${SOURCE_DIR[@]}`
    [ "$CODE"=="0" ] && echo -e "--------------------------------------------\nFull_Backup SystemFilesBackup Successfully!"
  fi
}  
#PerformincrementalBACKUPFunctionCommand
Add_Backup(){
  cd $TARGET_DIR/$YEAR/$MONTH/$DAY;
  if [ -f $TARGET_DIR/$YEAR/$MONTH/$DAY/$FILES ];then
    read -p "$FILESAlreadyExists,overwriteconfirmationyesorno?:"SURE
    if [ $SURE=="no" -o $SURE=="n" ];then
      sleep 1;exit 0
    fi
    #Add_BackupFilesSystem
    if [ $WEEK -ne "7" ];then
      cd $TARGET_DIR/$YEAR/$MONTH/$DAY;tar -g $TARGET_DIR/snapshot -czvf $FILES`echo${SOURCE_DIR[@]}`
      [ "$CODE"=="0" ]&& echo -e "-----------------------------------------\nAdd_Backup SystemFilesBackup Successfully!"
    fi
  else
    if [ $WEEK -ne "7" ];then
      cd $TARGET_DIR/$YEAR/$MONTH/$DAY;tar -g $TARGET_DIR/snapshot -czvf $FILES`echo${SOURCE_DIR[@]}`
      [ "$CODE"=="0" ]&& echo -e "-------------------------------------------\nAdd_Backup SystemFilesBackup Successfully!"
    fi
  fi
}
Full_Backup;Add_Backup
      
